#!/bin/bash

cd ~/SAN/

python  main_molhiv.py --config 'configs/MOLHIV/optimized'
python  main_molhiv.py --config 'configs/MOLHIV/optimized'
python  main_molhiv.py --config 'configs/MOLHIV/optimized'
python  main_molhiv.py --config 'configs/MOLHIV/optimized'



