#!/bin/bash

cd ~/SAN/

python  main_molhiv.py --config 'configs/MOLHIV/ablation/full/1e-4/node'
python  main_molhiv.py --config 'configs/MOLHIV/ablation/full/1e-4/node'
python  main_molhiv.py --config 'configs/MOLHIV/ablation/full/1e-4/node'
python  main_molhiv.py --config 'configs/MOLHIV/ablation/full/1e-4/node'



