#!/bin/bash

cd ~/SAN/

python  main_molhiv.py --config 'configs/MOLHIV/ablation/sparse/none'
python  main_molhiv.py --config 'configs/MOLHIV/ablation/sparse/none'
python  main_molhiv.py --config 'configs/MOLHIV/ablation/sparse/none'
python  main_molhiv.py --config 'configs/MOLHIV/ablation/sparse/none'
