#!/bin/bash

cd ~/SAN/

python  main_molpcba.py --config 'configs/MOLPCBA/optimized'
python  main_molpcba.py --config 'configs/MOLPCBA/optimized'
python  main_molpcba.py --config 'configs/MOLPCBA/optimized'
python  main_molpcba.py --config 'configs/MOLPCBA/optimized'



