#!/bin/bash
#SBATCH --job-name=zinc_sparse_node
#SBATCH --output=%x-%j.output.txt
#SBATCH --error=%x-%j.error.txt
#SBATCH --cpus-per-task=4
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --time=48:00:00
#SBATCH --mem=24Gb

source ~/venv/bin/activate
module load cuda/10.2

cd ~/SAN/

python  main_molhiv.py --config 'configs/MOLHIV/ablation/sparse/node'
python  main_molhiv.py --config 'configs/MOLHIV/ablation/sparse/node'
python  main_molhiv.py --config 'configs/MOLHIV/ablation/sparse/node'
python  main_molhiv.py --config 'configs/MOLHIV/ablation/sparse/node'
