#!/bin/bash
#SBATCH --account=rrg-bengioy-ad
#SBATCH --job-name=zinc_full_node
#SBATCH --output=%x-%j.output.txt
#SBATCH --error=%x-%j.error.txt
#SBATCH --cpus-per-task=4
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --time=12:00:00
#SBATCH --mem=12Gb

source ~/venv/bin/activate
cd ~/SAN/

python  main_ZINC_graph_regression.py --seed 41 --config 'configs/ZINC/optimized'
python  main_ZINC_graph_regression.py --seed 55 --config 'configs/ZINC/optimized'
python  main_ZINC_graph_regression.py --seed 13 --config 'configs/ZINC/optimized'
python  main_ZINC_graph_regression.py --seed 88 --config 'configs/ZINC/optimized'



