#!/bin/bash
#SBATCH --job-name=zinc_full_node
#SBATCH --output=%x-%j.output.txt
#SBATCH --error=%x-%j.error.txt
#SBATCH --cpus-per-task=4
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --time=48:00:00
#SBATCH --mem=24Gb

source ~/venv/bin/activate
module load cuda/10.2

cd ~/SAN/

python  main_ZINC_graph_regression.py --seed 41 --config 'configs/ZINC/ablation/full/1e-8/node'
python  main_ZINC_graph_regression.py --seed 55 --config 'configs/ZINC/ablation/full/1e-8/node'
python  main_ZINC_graph_regression.py --seed 13 --config 'configs/ZINC/ablation/full/1e-8/node'
python  main_ZINC_graph_regression.py --seed 88 --config 'configs/ZINC/ablation/full/1e-8/node'



