#!/bin/bash

cd ~/SAN/

python  main_ZINC_graph_regression.py --seed 41 --config 'configs/ZINC/ablation/full/1e-2/node'
python  main_ZINC_graph_regression.py --seed 55 --config 'configs/ZINC/ablation/full/1e-2/node'
python  main_ZINC_graph_regression.py --seed 13 --config 'configs/ZINC/ablation/full/1e-2/node'
python  main_ZINC_graph_regression.py --seed 88 --config 'configs/ZINC/ablation/full/1e-2/node'



